name: Deploy Github Pages

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: yuki-dl/shift-schedule-savior-p
          token: ${{ secrets.ORG_GITHUB_PAT }}
          path: pages
          ref: "gh-pages"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Cache
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build web pages
        run: trunk build --release

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist
          clean: false
